### ISSUE TITLE
Haraka can't connect with RabbitMQ 

### ISSUE THREAD

**Issue by savelmtr** [haraka/Haraka#2898]
When I try to start Haraka with RabbitMQ as database for plugin queue/rabbitmq_amqplib, I get this error:
`haraka_1    | [ERROR] [-] [queue/rabbitmq_amqplib] Connection to rabbitmq failed: Error: connect ECONNREFUSED 127.0.0.1:5672`

I don't know how this is possible. Let's see my docker-compose:
```
version: '3.7'
services:
  haraka:
    build: .
    ports:
      - 25:8025
    environment:
      - AMQP_RECEIVE_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=haraka
    expose:
      - 5672
```

Also, here is my rabbitmq.ini:
```
[rabbitmq]
  ; Connection
  ; Protocol. Either "amqp" or "amqps"
  protocol = amqps
  host = rabbitmq
  port = 5672
  ;Virtual Host. Start with "/". Leave blank or not use if you don't want to use virtual hosts.
  vhost = /haraka
  ;Credentials
  user = guest
  password = guest
  ; Exchange
  exchangeName  = email_messages
  exchangeType = direct
  ; Queue
  queueName = emails
  deliveryMode = 2
  confirm = true
  durable = true
  autoDelete = false
```

And, finally, here is my Dockerfile:
```
# pull official base image
FROM node:alpine

# install haraka
# --no-cache: download package index on-the-fly, no need to cleanup afterwards
# --virtual: bundle packages, remove whole bundle at once, when done
RUN apk --no-cache --virtual build-dependencies add python make g++ 
RUN npm install --quiet -g Haraka amqplib\
	&& npm cache clean --force \
    && apk del build-dependencies \
    && apk add openssl

USER node

RUN mkdir /home/node/.npm-global \
	&& mkdir /home/node/haraka
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN haraka -i /home/node/haraka \
	&& touch /home/node/haraka/config/loglevel \
	&& echo 'DEBUG' > /home/node/haraka/config/loglevel

COPY smtp.ini /home/node/haraka/config/smtp.ini
COPY plugins /home/node/haraka/config/plugins
COPY auth_flat_file.ini /home/node/haraka/config/auth_flat_file.ini
COPY tls_key.pem /home/node/haraka/config/tls_key.pem 
COPY tls_cert.pem /home/node/haraka/config/tls_cert.pem
COPY rabbitmq.ini /home/node/home/config/rabbitmq.ini

EXPOSE 8025

CMD ["haraka", "-c", "/home/node/haraka"]
```

Obviously, this system doesn't work.
I just have no idea, where I've failed.

**Comment by msimerson** [comment]
Sorry, Docker networking is not on topic here.

**Comment by AmreeshTyagi** [comment]
Expose is just used for label or information purpose only in Dockerfile. See official docker reference about EXPOSE.
Try binding rabbit service **port** as well like this. 

```
version: '3.7'
services:
  haraka:
    build: .
    ports:
      - 25:8025
    environment:
      - AMQP_RECEIVE_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_VHOST=haraka
    ports:
      - 5672:5672
```
